import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";


export const metadata: Metadata = {
  title: "𝕳𝖆𝖈𝖐𝖊𝖗 𝕭𝖎𝖔",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <div className="mt-4">
          {children}
        </div>
      </body>
    </html>
  );
}
